# Purpose: Define Secret for MongoDB
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongodb-root-password: {{ .Values.secret.rootPassword | b64enc | quote }}
  mongodb-password: {{ .Values.secret.password | b64enc | quote }}