# Purpose: Define Deployment for the application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: node-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
          - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          env:
            - name: MONGO_URI
              value: "{{ .Values.secret.mongoUri }}"
              # value: "mongodb://mongodb:27017/mydatabase"
              

