apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-only-mongodb-binding
  namespace: {{ .Values.namespace.name }}
subjects:
- kind: ServiceAccount
  name: app-serviceaccount
  namespace: {{ .Values.namespace.name }}
roleRef:
  kind: Role
  name: read-only-mongodb
  apiGroup: rbac.authorization.k8s.io
