apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
data:
  mongo-uri: {{ .Values.secret.mongoUri | b64enc }}
  root-password: {{ .Values.secret.rootPassword | b64enc | quote }}
  password: {{ .Values.secret.password | b64enc | quote }}
