# Purpose: Define Service for the application
apiVersion: v1
kind: Service
metadata:
  name: node-app
spec:
  # type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: node-app
