# Purpose: Define Service for MongoDB
apiVersion: v1
kind: Service
metadata:
  name: node-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: node-app