# Purpose: Define default values for the deployment
replicaCount: 1
image:
  repository: sdikman/node-app
  pullPolicy: IfNotPresent
  tag: "latest"
service:
  type: ClusterIP
  port: 8080
route:
  enabled: true
  # host: node-app.local
secret:
  mongoUri: "mongodb://mongodb:27017/mydatabase"
  rootPassword: "root-password"
  password: "password"
namespace:
  name: my-web-project